### ISSUE TITLE
Track callback not based on request.

### ISSUE THREAD

**Issue by RohitRox** [segmentio/analytics.js-core#10]
Correct me if I'm wrong, but it is my understanding that the callback passed into analytics.track is based on an arbitrary amount timeout rather than the status of the xhr request.  Is there a reason for this? could it be changed? Currently there is no way to verify a tracking request has been made before executing my callback.  We are using the customer.io integration and would like to have more confidence in our tracking events.

**Comment by hankim813** [comment]
@RohitRox I know this is very late but that is correct. The arbitrary timeout is `300ms` as seen [here](https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L61) which is used [here](https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L573).

We definitely can't wait for all integrations to make their HTTP requests given that our library is async by nature and wouldn't want to block your app because say one integration had some server downtime/delay. Furthermore, many integration libraries are kind of blackboxes and we wouldn't exactly know what constitutes a "completion". Most integration libraries we use under the hood don't provide completion callbacks/hooks so there's really no way for us to reliably know what "done" would mean.

Even if we could wait for integrations to make http requests we wouldn't necessarily know what status codes indicate success for that partner, or how many HTTP requests need to be made to signal completion.

Waiting 300ms isn't ideal but it's not a terrible workaround either since the alternative could be that 
you could call back immediately and basically be guaranteed that nothing has completed, or wait and have a much better likelihood that the call is complete.

If you believe that 300ms is NOT enough time, then you can always [configure](https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L528) this "arbitrary" timeout: `analytics.timeout = 600`
