### ISSUE TITLE
Don't use new Function()

### ISSUE THREAD

**Issue by denkristoffer** [segmentio/analytics.js-core#101]
The distributed version of analytics.js currently uses `new Function()`, which doesn't work with Content-Security-Policy headers unless you add `'unsafe-eval'` to `script-src`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions

Moved from https://github.com/segmentio/analytics.js/issues/578

**Comment by f2prateek** [comment]
Can you clarify where you are seeing this? I am not seeing this in this codebase.

**Comment by denkristoffer** [comment]
I'm seeing it in the minified version hosted by Segment: https://cdn.segment.com/analytics.js/v1/xjsFGeAAQGSKNKED0wnvAyaScd0ZXJnP/analytics.min.js

**Comment by f2prateek** [comment]
I'll check it out!

**Comment by f2prateek** [comment]
This is due to a transitive dependency on this package https://github.com/ndhoule/arity, from https://github.com/ndhoule/arity/blob/master/index.js#L69.

```
+-- @segment/analytics.js-core@3.7.2
| +-- @ndhoule/after@1.0.0
| | `-- @ndhoule/arity@2.0.0
```

Here's a few possible options as I see it:
* replace `after` package (https://github.com/segmentio/analytics.js-core/blob/54d2011c83ada694984ab30ec6f6dc4da6acac80/lib/analytics.js#L15) with something else
* send a PR to https://github.com/ndhoule/arity and update the version here

I'm also not that familiar with `Content-Security-Policy` headers - could you describe how this is sued and how it applies to analytics.js? I'm a bit surprised this is the first time we've heard about it from a customer...

**Comment by denkristoffer** [comment]
Of course, sorry! It's just an HTTP header sent by the server: `Content-Security-Policy: <insert policy>`. For instance, `Content-Security-Policy: default-src https:; script-src 'nonce-{random}'; object-src 'none'` (from https://csp.withgoogle.com/docs/index.html)

Here's Google's guide: https://developers.google.com/web/fundamentals/security/csp/

**Comment by erikfrisk** [comment]
Any new info on this? We have the same problem. We're adding a Content-Security-Policy header when serving our web app and to use analytics.js we have to add `'unsafe-eval'` to our `script-src` directive.

**Comment by danieljackins** [comment]
The CSP issue is deeply rooted in the JS ecosystem and transitive dependencies. We have done our best effort to identify and fix this issue under core AJS code as well as replaced direct dependency on packages causing this. However, this issue is not fully resolved due to other dependencies. We look to completely resolve this issue in the coming months.

**Comment by elesueur** [comment]
@danieljackins Is there another issue tracking your ongoing efforts to resolve this issue that I can track?
