### ISSUE TITLE
'Unexpected token export' in test

### ISSUE THREAD

**Issue by pcothenet** [segmentio/analytics.js-core#18]
Hi team,

I'm using a fork of analytics.js-core and the recent changes to the bind-all repo (which I think was transferred) made it impossible to build our version. I updated to yesterday changes (which appear to fix that problem) but the tests are failing (`make test`) and `make test browser`). Seems they're also failing in CircleCI on your side.

Seems like there's a package using an 'export' construction that the browser doesn't like. 

Wondering if that's something you were aware of and how to fix it?

Cheers

**Comment by ndhoule** [comment]
Thanks for the report, @pcothenet. The last two patch releases pin or replace packages that have introduced breaking changes upstream and should fix the issues you're seeing. Rebase your branch from upstream and run `make distclean` to purge out all the old packages, and `make test-browser` to verify it's building for you.

I'm going to close this issue, but please re-open it if you do the above and it doesn't fix your issue.

CircleCI is broken due to an upstream node module publishing a breaking change as a non-major semver release; I'm looking into an easy fix for this, but as we're in the final stretches of converting analytics.js-core to Browserify (which requires swapping out all our test tooling, fixing the issue in the process 😛 ) it's a low priority for us right now. Let me know if this is causing you significant problems and I can look into it further.

**Comment by pcothenet** [comment]
Looks like the compiled version work. I was a bit thrown off by the failed
test (also failing on local). Low priority on my end too.

**Comment by ndhoule** [comment]
Good to hear it's working now. The testing and build harnesses are definitely showing their age—I'm looking forward to replacing them with modern, community-supported tools like Browserify and Karma. That's coming down the pipe very soon.

If the priority changes for you, please do follow up—again, I'm happy to investigate if it'll help you out.
