### ISSUE TITLE
Default Context

### ISSUE THREAD

**Issue by gjohnson** [segmentio/analytics.js-core#26]
Hey everyone!

What do you all think about adding the ability to pass a default context? The use case is needing to pass the same context to _all_ events, implicitly, so we don't copy-pasta it all over.

It seems we could almost do this with `.initialize()`, but that is already being called by the hosted version of analytics.js via the cdn. So maybe adding something like:

``` js
analytics.options = {
  context: {
    foo: bar
  }
}
analytics.load('xxx')
analytics.page()
```

I _think_ this would be possible by just merging here instead of assigning? https://github.com/segmentio/analytics.js-core/blob/b344cef8dfc32405802f53109c27a71df9d789a6/lib/analytics.js#L551

I'm glad to make the change(s) if you all are down for them :-)

**Comment by f2prateek** [comment]
I think it's reasonable to support this - our Android library already does and it's great for events that are automatically instrumented by the library.

Ideally we'd support it via middlewares as we're planning to do on mobile, but I think that's a significantly bigger change.

I'll let @tsholmes and @ndhoule chime in on what they'd like the implementation in a.js to look like.

**Comment by gjohnson** [comment]
Any thoughts on this?

**Comment by tsholmes** [comment]
This would definitely be useful for a handful of different use cases. We would just need to cdn to have the `options` field of the snippet pass through to `analytics._options`. If you could submit a PR to make `analytics._options` merge with `this.options`, we can make the changes on our end to call it in the cdn served analytics.js

**Comment by ndhoule** [comment]
Seems useful to me. I'd like to see it implemented the same way as Android does it; moving toward a more consistent experience across libraries is generally a good thing.

@f2prateek how do we do it on Android (mostly, how do we handle nested data)? Do we do a deep merge?

Ideally I'd also like to see this implemented in a way that makes the merging customizable (i.e. middleware), since a deep merge strategy is probably not going to work for everyone—but I'd rather implement that later, when mobile libraries implement it, to keep experience consistent.

**Comment by f2prateek** [comment]
We do a shallow merge on Android so `{ a : { b : c } }` (global) + `{ a: { d: e } }` (local) would be recorded as `{ a : { d : e } }`. Not necessarily by design, but just that's because what the default Java [`Map#putAll`](https://docs.oracle.com/javase/7/docs/api/java/util/Map.html#putAll(java.util.Map)) implementation does.

**Comment by gjohnson** [comment]
Sounds good, thanks guys!

**Comment by malthejorgensen** [comment]
Just to make sure, I believe this would also this problem I'm having:

https://community.segment.com/t/m2m3hl

Where I cannot filter what integrations are sent on the initial page event.

**Comment by f2prateek** [comment]
Tracking in https://segment.atlassian.net/browse/LIB-145

**Comment by danieljackins** [comment]
Closing this issue. If this is still a problem, please reopen so that we can get it properly reprioritized.

**Comment by ianks** [comment]
@danieljackins this would be incredibly useful for us, can this be re-opened?
