### ISSUE TITLE
'global' id in HTML tag causes analytics.js to fail badly

### ISSUE THREAD

**Issue by disruptek** [segmentio/analytics.js-core#29]
If you, as I do, have a page with, say, a `<div id="global">...</div>` then analytics.js will load and run via the snippet, but will not overwrite the `window.analytics` variable and playback the stubbed call queue.  A call to `page()` will be made with the defaults, but that's the only sign that anything at all happened.

And, yes, this absolutely gave me fits while trying to debug...

**Comment by tsholmes** [comment]
This is due to the lovely implicit id references and an issue in the `insert-module-globals` module that browserify uses to fill global references. would be fixed by https://github.com/substack/insert-module-globals/pull/48/files if it ever merges. I can put in a workaround for this in our browserify process for analytics.js for now. I'll update you when its deployed

**Comment by disruptek** [comment]
Thanks; that sounds better than an update to the docs. :wink:

**Comment by tsholmes** [comment]
New version deployed. Let me know if its fixed for you

**Comment by disruptek** [comment]
Sorry; worked around this and didn't bother to update the ticket.  It appears fixed, thanks.  😄
